// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/v1/dto/reply_comment.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplyCommentItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Subject int64 `protobuf:"varint,2,opt,name=Subject,proto3" json:"Subject,omitempty"`
	Parent  int64 `protobuf:"varint,3,opt,name=Parent,proto3" json:"Parent,omitempty"`
	Floor   int64 `protobuf:"varint,4,opt,name=Floor,proto3" json:"Floor,omitempty"`
	UserID  int64 `protobuf:"varint,5,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Replyto int64 `protobuf:"varint,6,opt,name=Replyto,proto3" json:"Replyto,omitempty"`
	Like    int64 `protobuf:"varint,7,opt,name=Like,proto3" json:"Like,omitempty"`
	Hate    int64 `protobuf:"varint,8,opt,name=Hate,proto3" json:"Hate,omitempty"`
	Count   int64 `protobuf:"varint,9,opt,name=Count,proto3" json:"Count,omitempty"`
	State   int64 `protobuf:"varint,10,opt,name=State,proto3" json:"State,omitempty"`
}

func (x *ReplyCommentItem) Reset() {
	*x = ReplyCommentItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_dto_reply_comment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyCommentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyCommentItem) ProtoMessage() {}

func (x *ReplyCommentItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_dto_reply_comment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyCommentItem.ProtoReflect.Descriptor instead.
func (*ReplyCommentItem) Descriptor() ([]byte, []int) {
	return file_proto_v1_dto_reply_comment_proto_rawDescGZIP(), []int{0}
}

func (x *ReplyCommentItem) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ReplyCommentItem) GetSubject() int64 {
	if x != nil {
		return x.Subject
	}
	return 0
}

func (x *ReplyCommentItem) GetParent() int64 {
	if x != nil {
		return x.Parent
	}
	return 0
}

func (x *ReplyCommentItem) GetFloor() int64 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *ReplyCommentItem) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ReplyCommentItem) GetReplyto() int64 {
	if x != nil {
		return x.Replyto
	}
	return 0
}

func (x *ReplyCommentItem) GetLike() int64 {
	if x != nil {
		return x.Like
	}
	return 0
}

func (x *ReplyCommentItem) GetHate() int64 {
	if x != nil {
		return x.Hate
	}
	return 0
}

func (x *ReplyCommentItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ReplyCommentItem) GetState() int64 {
	if x != nil {
		return x.State
	}
	return 0
}

type ReplyCommentContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	//    int64 Index = 2;
	Content  []byte `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	IP       string `protobuf:"bytes,4,opt,name=IP,proto3" json:"IP,omitempty"`
	Platform int64  `protobuf:"varint,5,opt,name=Platform,proto3" json:"Platform,omitempty"`
	Device   string `protobuf:"bytes,6,opt,name=Device,proto3" json:"Device,omitempty"`
	State    int64  `protobuf:"varint,7,opt,name=State,proto3" json:"State,omitempty"`
}

func (x *ReplyCommentContent) Reset() {
	*x = ReplyCommentContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_dto_reply_comment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyCommentContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyCommentContent) ProtoMessage() {}

func (x *ReplyCommentContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_dto_reply_comment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyCommentContent.ProtoReflect.Descriptor instead.
func (*ReplyCommentContent) Descriptor() ([]byte, []int) {
	return file_proto_v1_dto_reply_comment_proto_rawDescGZIP(), []int{1}
}

func (x *ReplyCommentContent) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ReplyCommentContent) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ReplyCommentContent) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *ReplyCommentContent) GetPlatform() int64 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *ReplyCommentContent) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *ReplyCommentContent) GetState() int64 {
	if x != nil {
		return x.State
	}
	return 0
}

type ReplyCommentSubject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ObjType int64 `protobuf:"varint,2,opt,name=ObjType,proto3" json:"ObjType,omitempty"`
	ObjID   int64 `protobuf:"varint,3,opt,name=ObjID,proto3" json:"ObjID,omitempty"`
	Like    int64 `protobuf:"varint,4,opt,name=Like,proto3" json:"Like,omitempty"`
	Hate    int64 `protobuf:"varint,5,opt,name=Hate,proto3" json:"Hate,omitempty"`
	Count   int64 `protobuf:"varint,6,opt,name=Count,proto3" json:"Count,omitempty"`
}

func (x *ReplyCommentSubject) Reset() {
	*x = ReplyCommentSubject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_dto_reply_comment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyCommentSubject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyCommentSubject) ProtoMessage() {}

func (x *ReplyCommentSubject) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_dto_reply_comment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyCommentSubject.ProtoReflect.Descriptor instead.
func (*ReplyCommentSubject) Descriptor() ([]byte, []int) {
	return file_proto_v1_dto_reply_comment_proto_rawDescGZIP(), []int{2}
}

func (x *ReplyCommentSubject) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ReplyCommentSubject) GetObjType() int64 {
	if x != nil {
		return x.ObjType
	}
	return 0
}

func (x *ReplyCommentSubject) GetObjID() int64 {
	if x != nil {
		return x.ObjID
	}
	return 0
}

func (x *ReplyCommentSubject) GetLike() int64 {
	if x != nil {
		return x.Like
	}
	return 0
}

func (x *ReplyCommentSubject) GetHate() int64 {
	if x != nil {
		return x.Hate
	}
	return 0
}

func (x *ReplyCommentSubject) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ReplyComment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item    *ReplyCommentItem    `protobuf:"bytes,1,opt,name=Item,proto3" json:"Item,omitempty"`
	Content *ReplyCommentContent `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *ReplyComment) Reset() {
	*x = ReplyComment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_v1_dto_reply_comment_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplyComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyComment) ProtoMessage() {}

func (x *ReplyComment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_dto_reply_comment_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyComment.ProtoReflect.Descriptor instead.
func (*ReplyComment) Descriptor() ([]byte, []int) {
	return file_proto_v1_dto_reply_comment_proto_rawDescGZIP(), []int{3}
}

func (x *ReplyComment) GetItem() *ReplyCommentItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *ReplyComment) GetContent() *ReplyCommentContent {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_proto_v1_dto_reply_comment_proto protoreflect.FileDescriptor

var file_proto_v1_dto_reply_comment_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x74, 0x6f, 0x2f, 0x72,
	0x65, 0x70, 0x6c, 0x79, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x16, 0x6a, 0x76, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x64, 0x74, 0x6f, 0x22, 0xf0, 0x01, 0x0a, 0x10, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12,
	0x18, 0x0a, 0x07, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x50, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x46, 0x6c, 0x6f, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x18, 0x0a, 0x07, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x74, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x69, 0x6b,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x48, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x48, 0x61, 0x74,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x99, 0x01,
	0x0a, 0x13, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x12,
	0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x93, 0x01, 0x0a, 0x13, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x62, 0x6a, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x4f, 0x62, 0x6a, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4f,
	0x62, 0x6a, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x4f, 0x62, 0x6a, 0x49,
	0x44, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x69, 0x6b, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x48, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x93, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x3c, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28,
	0x2e, 0x6a, 0x76, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x64, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x45,
	0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2b, 0x2e, 0x6a, 0x76, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x64, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x69, 0x6e, 0x76, 0x65, 0x69, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_v1_dto_reply_comment_proto_rawDescOnce sync.Once
	file_proto_v1_dto_reply_comment_proto_rawDescData = file_proto_v1_dto_reply_comment_proto_rawDesc
)

func file_proto_v1_dto_reply_comment_proto_rawDescGZIP() []byte {
	file_proto_v1_dto_reply_comment_proto_rawDescOnce.Do(func() {
		file_proto_v1_dto_reply_comment_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_v1_dto_reply_comment_proto_rawDescData)
	})
	return file_proto_v1_dto_reply_comment_proto_rawDescData
}

var file_proto_v1_dto_reply_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_v1_dto_reply_comment_proto_goTypes = []interface{}{
	(*ReplyCommentItem)(nil),    // 0: jv.microservice.v1.dto.ReplyCommentItem
	(*ReplyCommentContent)(nil), // 1: jv.microservice.v1.dto.ReplyCommentContent
	(*ReplyCommentSubject)(nil), // 2: jv.microservice.v1.dto.ReplyCommentSubject
	(*ReplyComment)(nil),        // 3: jv.microservice.v1.dto.ReplyComment
}
var file_proto_v1_dto_reply_comment_proto_depIdxs = []int32{
	0, // 0: jv.microservice.v1.dto.ReplyComment.Item:type_name -> jv.microservice.v1.dto.ReplyCommentItem
	1, // 1: jv.microservice.v1.dto.ReplyComment.Content:type_name -> jv.microservice.v1.dto.ReplyCommentContent
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_v1_dto_reply_comment_proto_init() }
func file_proto_v1_dto_reply_comment_proto_init() {
	if File_proto_v1_dto_reply_comment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_v1_dto_reply_comment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyCommentItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_dto_reply_comment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyCommentContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_dto_reply_comment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyCommentSubject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_v1_dto_reply_comment_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplyComment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_v1_dto_reply_comment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_dto_reply_comment_proto_goTypes,
		DependencyIndexes: file_proto_v1_dto_reply_comment_proto_depIdxs,
		MessageInfos:      file_proto_v1_dto_reply_comment_proto_msgTypes,
	}.Build()
	File_proto_v1_dto_reply_comment_proto = out.File
	file_proto_v1_dto_reply_comment_proto_rawDesc = nil
	file_proto_v1_dto_reply_comment_proto_goTypes = nil
	file_proto_v1_dto_reply_comment_proto_depIdxs = nil
}
