// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package users

import (
	"database/sql"
	"time"
)

// 用户表/2022-07-18
type User struct {
	// 主键/2022-07-18
	ID int64
	// 用户名/2022-07-18
	Username string
	// 密码/2022-07-18
	Password string
	// 手机号码/2022-07-18
	Telnumber sql.NullString
	// 邮箱/2022-07-18
	Email sql.NullString
	// 密码对应的盐值/2022-07-18
	Salt string
	// 性别/0未知/1男/2女/2022-07-18
	Gender int32
	// 用户状态/1启用/2永久冻结/2022-07-18
	Status int32
	// 数据库创建时间/2022-07-18
	CreatedAt time.Time
	// 创建者/2022-07-18
	CreateBy int64
	// 创建时间/2022-07-18
	CreateTime int64
	// 数据库修改时间
	UpdatedAt time.Time
	// 最后修改者/2022-07-18
	LastModifyBy sql.NullInt64
	// 最后修改时间/2022-07-18
	LastModifyTime sql.NullInt64
}
